publisher:
  name: dReader
  address: 5e7RkK7cJaoAEx2F5wRqauY9556exJtWn4dv2nQFF4X3
  website: https://dreader.io/
  email: dapp.store@dreader.io
  media:
    - purpose: icon
      uri: ./512x512_rounded.png
app:
  name: dReader
  address: FHJRMnXxYNccbr3CPBT76Zq7jejcbEVZhgqHEfTv3La4
  android_package: io.app.dreader
  urls:
    license_url: https://github.com/d-reader-organization/d-reader-flutter/blob/main/LICENSE
    copyright_url: https://github.com/d-reader-organization/d-reader-flutter/blob/main/LICENSE
    privacy_policy_url: https://dreader.app/privacy-policy
    website: https://dreader.io/
  media:
    - purpose: icon
      uri: ./512x512_rounded.png
release:
  address: 3Q7n6gsQu4fvAcoiLhxFkeV7P3a24x9ggJ2e7XuqpLtn
  media:
    - purpose: icon
      uri: ./512x512_rounded.png
    - purpose: screenshot
      uri: ./screenshots/1.png
    - purpose: screenshot
      uri: ./screenshots/2.png
    - purpose: screenshot
      uri: ./screenshots/3.png
    - purpose: screenshot
      uri: ./screenshots/4.png
    - purpose: screenshot
      uri: ./screenshots/5.png
  files:
    - purpose: install
      uri: ./dReader.apk
  catalog:
    en-US:
      name: dReader
      short_description: Digital comic book store
      long_description: Platform for discovering, trading, collecting, and reading digital graphic novels
      new_in_version: Consolidate auth flow
      saga_features: Improve dialogs, mint flow and e-reader
solana_mobile_dapp_publisher_portal:
  google_store_package: io.app.dreader
  testing_instructions: Run the app
lastSubmittedVersionOnChain:
  address: 3Q7n6gsQu4fvAcoiLhxFkeV7P3a24x9ggJ2e7XuqpLtn
  version_code: 2046
  apk_hash: j/FCwOXdrAuf9yYDytrNYZxKB2Zdm9xSqq+00ynvmkw=
lastUpdatedVersionOnStore:
  address: 3Q7n6gsQu4fvAcoiLhxFkeV7P3a24x9ggJ2e7XuqpLtn
