publisher:
  name: dReader
  address: 5e7RkK7cJaoAEx2F5wRqauY9556exJtWn4dv2nQFF4X3
  website: https://dreader.io/
  email: dapp.store@dreader.io
  media:
    - purpose: icon
      uri: ./512x512_rounded.png
app:
  name: dReader
  address: FHJRMnXxYNccbr3CPBT76Zq7jejcbEVZhgqHEfTv3La4
  android_package: io.app.dreader
  urls:
    license_url: https://github.com/d-reader-organization/d-reader-flutter/blob/main/LICENSE
    copyright_url: https://github.com/d-reader-organization/d-reader-flutter/blob/main/LICENSE
    privacy_policy_url: https://dreader.app/privacy-policy
    website: https://dreader.io/
  media:
    - purpose: icon
      uri: ./512x512_rounded.png
release:
  address: 7Yksoshaa7rPKgLdvQ7Egp99QkwHKvdr3CoXc2x52EBp
  media:
    - purpose: icon
      uri: ./512x512_rounded.png
    - purpose: screenshot
      uri: ./screenshots/1.png
    - purpose: screenshot
      uri: ./screenshots/2.png
    - purpose: screenshot
      uri: ./screenshots/3.png
    - purpose: screenshot
      uri: ./screenshots/4.png
    - purpose: screenshot
      uri: ./screenshots/5.png
  files:
    - purpose: install
      uri: ./dReader.apk
  catalog:
    en-US:
      name: dReader
      short_description: Digital comic book store
      long_description: Platform for discovering, trading, collecting, and reading digital graphic novels
      new_in_version: Update comic issue model, connect wallet endpoint and search query param
      saga_features: Exclusive early access, free/discounted collectible comics
solana_mobile_dapp_publisher_portal:
  google_store_package: io.app.dreader
  testing_instructions: Run the app
lastSubmittedVersionOnChain:
  address: 7Yksoshaa7rPKgLdvQ7Egp99QkwHKvdr3CoXc2x52EBp
  version_code: 2054
  apk_hash: i4zrNVTTnu9d2SN3VCt/YDg83ijXSZKdM5ilkNJQnPs=
lastUpdatedVersionOnStore:
  address: 7Yksoshaa7rPKgLdvQ7Egp99QkwHKvdr3CoXc2x52EBp
