publisher:
  name: dReader
  address: 5e7RkK7cJaoAEx2F5wRqauY9556exJtWn4dv2nQFF4X3
  website: https://dreader.io/
  email: dapp.store@dreader.io
  media:
    - purpose: icon
      uri: ./512x512.png
app:
  name: dReader
  address: FHJRMnXxYNccbr3CPBT76Zq7jejcbEVZhgqHEfTv3La4
  android_package: io.app.dreader
  urls:
    license_url: >-
      https://github.com/d-reader-organization/d-reader-flutter/blob/main/LICENSE
    copyright_url: >-
      https://github.com/d-reader-organization/d-reader-flutter/blob/main/LICENSE
    privacy_policy_url: https://dreader.io/
    website: https://dreader.io/
  media:
    - purpose: icon
      uri: ./512x512.png
release:
  address: 6ZcjXdg8pdCTAUjJUaJQzvzRAbbJc3A8U3grn2iGVqzg
  media:
    - purpose: icon
      uri: ./512x512.png
    - purpose: screenshot
      uri: ./screenshots/1.png
    - purpose: screenshot
      uri: ./screenshots/2.png
    - purpose: screenshot
      uri: ./screenshots/3.png
    - purpose: screenshot
      uri: ./screenshots/4.png
    - purpose: screenshot
      uri: ./screenshots/5.png
    - purpose: screenshot
      uri: ./screenshots/1.png
    - purpose: screenshot
      uri: ./screenshots/feature_graphic.png
  files:
    - purpose: install
      uri: ./dReader.apk
  catalog:
    en-US:
      name: dReader
      short_description: Discover a new world of comic collecting
      long_description: >-
        Platform for discovering, trading, collecting, and reading digital
        graphic novels
      new_in_version: Initial alpha release
      saga_features: Exclusive early access, free/discounted collectible comics
solana_mobile_dapp_publisher_portal:
  google_store_package: io.app.dreader
  testing_instructions: Run the app
