
name: Dev - Upload to Firebase Distribution

on:
  push: 
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]


jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '17.x'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: 'Create env file'
        run: |
          touch .env
          echo sentryDsn=${{ secrets.SENTRY_DSN }} >> .env
          cat .env

      # - name: Run tests
      #   run: flutter test

      - name: Build android apk and appBundle
        run: make build-dev

      # - name: Build android ios
      #   run: flutter build ios --releasee --no-codesign